export type {
  ResumeData,
  PersonalInfo,
  ExperienceItem,
  EducationItem,
  SkillGroup,
  ProjectItem,
  CertificationItem,
  LanguageItem,
  CefrLevel,
  Cefr,
  LinkItem,
  TemplateId,
  AccentColor,
  EuropassStyle,
  SectionKey,
} from "@/lib/validations/resume";
